### ISSUE TITLE
Exported PNG has changed colours

### ISSUE THREAD

**Issue by andreisocaciu** [meltingice/psd.js#189]
When exporting a layer as PNG, the colours change slightly.
I tried the suggestion from #110 but with no success. PNG is still different.

Original file
![EASI-300X600 - original](https://user-images.githubusercontent.com/15923667/86232548-c1dd0080-bb9c-11ea-907f-e49b27a2d74a.png)

Exported from psd.js
![EASI-300X600 - from psdjs](https://user-images.githubusercontent.com/15923667/86232553-c43f5a80-bb9c-11ea-9889-54e60b483623.png)

**Comment by iWantARagdoll** [comment]
Have you solved your problem? I have this problem, too

**Comment by andreisocaciu** [comment]
No, I couldn't find the solution.

**Comment by iWantARagdoll** [comment]
> No, I couldn't find the solution.

In Photoshop, select Edit > Color Settings > workspace: RGB select sRGB, and then open PSD again. At this time, the embedded configuration file does not match. Then select: convert the document color to workspace, which seems to solve this problem, although I don't understand what it means:)

I guess it may be the problem of color area. In order to ensure that the color seen by the naked eye is the same, PS modified the value of pixels in the original image, but we get the original pixel value.

**Comment by andreisocaciu** [comment]
> > No, I couldn't find the solution.
> 
> In Photoshop, select Edit > Color Settings > workspace: RGB select sRGB, and then open PSD again. At this time, the embedded configuration file does not match. Then select: convert the document color to workspace, which seems to solve this problem, although I don't understand what it means:)
> 
> I guess it may be the problem of color area. In order to ensure that the color seen by the naked eye is the same, PS modified the value of pixels in the original image, but we get the original pixel value.

This worked for me, also.
![image](https://user-images.githubusercontent.com/15923667/86731772-8462f200-c038-11ea-9c88-32eca64aa63c.png)
