### ISSUE TITLE
Check if file is valid psd

### ISSUE THREAD

**Issue by are1000** [meltingice/psd.js#34]
How to check if a file `PSD.fromFile("path/to/invalid.psd")` is a valid psd?

**Comment by meltingice** [comment]
There are currently no checks internally that validate the PSD because, due to the lack of good documentation on the file format, the library takes a "best effort" approach to parsing. That said you can do:

``` js
var psd = PSD.fromFile("path/to/invalid.psd");
psd.parse();
assert(psd.header.sig === '8BPS');
```

While that doesn't validate the entire PSD, it does make sure that at least the PSD header is valid and that you are attempting to parse a PSD.

**Comment by meltingice** [comment]
Oh, and it's also possible to parse only the header if you want, which might avoid weird parsing errors that could cause infinite loops/exceptions/etc.

``` js
var psd = PSD.fromFile("path/to/invalid.psd");
psd.parseHeader();
assert(psd.header.sig === '8BPS');
```

However, if you do that, you'll have to recreate your PSD object and start parsing over from scratch if you wish to continue parsing.

**Comment by are-are-** [comment]
Thanks! That's exactly what I do in my code.

**Comment by fabulousduck** [comment]
This issue was resolved by @meltingice's answer and acknowledged by @are1000. Closing this.
