### ISSUE TITLE
Edit text Layer and Export it to PNG

### ISSUE THREAD

**Issue by mAmged** [meltingice/psd.js#35]
I tried a lot to do that but I couldn't,
How Can I change text value in a textLayer, and export it to png or save it as psd?
Thanks

**Comment by meltingice** [comment]
Due to the complexity involved, there are currently no write capabilities in psd.js. Any changes you make to the PSD data after parsing it will not be reflected in the exported images. Exported images are produced by parsing embedded bitmap image data, and are not rendered on the fly with any other data in the PSD.

**Comment by mAmged** [comment]
check this photopea.com it's fully js and very high performance
