### ISSUE TITLE
psd.tree().export() getting stuck 

### ISSUE THREAD

**Issue by benpptung** [meltingice/psd.js#90]
Hi, I am trying to use psd to replace imagemagick's identify() for psd file. Thank you for this excellent project!! I found it is much faster than imagemagick.identify().

However, when I tested it with some fake psd files, it seems the psd.js will be getting stuck.
Following please find how to reproduce the problem.

I am wondering if we can add some defensive codes to avoid `export()` getting stuck?
Thank you :)

```
'use strict';

const request = require('request');
const PSD = require('psd');
const Async = require('util-asyncflow');

var flow = new Async();
var fakefile = 'https://s3.amazonaws.com/tacolbiz/misc/car-photoshop-iff.iff';

flow.task(next=> {

  let s = request(fakefile);
  let buff = [];

  s.on('data', buf=> buff.push(buf))
    .on('end', _=> {
      buff = Buffer.concat(buff);
      next(null, buff);
    })
    .on('error', err=> next(err));

});

flow.wait(buff=> {

  let psd = new PSD(buff);
  psd.parse();

  let tree = psd.tree();

  console.log('will export() tree');

  tree = tree.export(); // getting stuck here.

  console.log('never see this');
});

flow.run(err=> console.error(err));
```

**Comment by fabulousduck** [comment]
Currently we do not check the signature of the file (which should be `8BPS` for PSD files) even tho we have it stored (https://github.com/meltingice/psd.js/blob/master/lib/psd/header.coffee#L32).

I assume this will be fixed in the rewrite @meltingice  ? But as that is not finished yet, i will see about making a PR that does the check.

With this check, it will fail on `let psd = new PSD(buff)` as the signature of the file does not match.

**Comment by fabulousduck** [comment]
Pr for this has been merged and the issue resolved. closing this
